# VisionX Default Configuration

model: yoloe-26m-seg.pt

prompts:
  - car
  - person
  - motorcycle

confidence: 0.5
save_video: true
save_crops: false
save_report: false
half: false
vid_stride: 1
show: false
