# VisionX Default Configuration

model: yoloe-26x-seg.pt

prompts:
  - car
  - person
  - motorcycle

confidence: 0.5
save_video: false
save_crops: false
save_report: true
half: false
vid_stride: 1
show: false
